### ISSUE TITLE
第一章第一节 图基础(图理论算法)

### ISSUE THREAD

**Issue by SOVLOOKUP** [SOVLOOKUP/front-opensource-learning#5]
写入到markdown: https://github.com/SOVLOOKUP/front-opensource-learning/blob/master/contents/Part-1/1.1%E5%9B%BE%E5%85%A5%E9%97%A8.md

**Comment by ghost** [comment]
有意向认领
我做过的相关项目：
https://github.com/YiAlpha/network-analysis-twitter
https://github.com/YiAlpha/auto-law-review

**Comment by SOVLOOKUP** [comment]
这两个项目都很棒，已star

第一章第一节的**书写建议**

### 教程主要目的

 - 让数据分析者从熟悉的数据分析内容开始，主要让初学者找到感觉，图分析的内容正好可以给大部分人即熟悉又新鲜的感觉。
 - 并且前端图分析也是基于基本的图算法进行的，为下面的实战打好基础
 
### 主要内容

以下是参考分节，具体小节划分可以自己安排

 - 认识图论
 - 图能解决什么问题
 - 图分析的现状
 - 基本的图算法

### 参考

1. 如何贡献：[贡献方法](https://github.com/SOVLOOKUP/front-opensource-learning/tree/master/contents#%E5%86%85%E5%AE%B9%E5%AF%BC%E8%88%AA)
2. 什么是图：[知识图谱学习路线](https://github.com/datawhalechina/team-learning-nlp/blob/master/KnowledgeGraph_Basic/task01.md#121-%E4%BB%80%E4%B9%88%E6%98%AF%E5%9B%BEgraph%E5%91%A2)

**Comment by SOVLOOKUP** [comment]
可以参考 https://zhuanlan.zhihu.com/p/132393588 内容

**Comment by SOVLOOKUP** [comment]
这个issue已与 #13 合并
